services:

  Ferdyrurka\CommandBus\CommandBusInterface:
    class: 'Ferdyrurka\CommandBus\CommandBus'
    autowire: true

  Ferdyrurka\CommandBus\Handler\CreateLogHandler:
    class: 'Ferdyrurka\CommandBus\Handler\CreateLogHandler'
    arguments:
      - '@Ferdyrurka\CommandBus\Manager\ElasticSearchManager'